### ISSUE TITLE
jitter from the CO2 sensor

### ISSUE THREAD

**Issue by franz134** [geerlingguy/airgradient-prometheus#24]
hey, 
I have assembled it 3 days ago and as the title said, my CO2 sensor (senseair s8) began the have some false measurements. 
So two afternoons in a row I got some measurements of 514 und -1 ppm yesterday and 516 und -1 today, which are false according to the course of the graph, and I only had the idea of unplugging it. 
Jeff and the datasheet of the sensor said that it might take a while till it's "calibrated" but has anyone else had such an experience?
I don't want to unplug it every day ^^

![image](https://user-images.githubusercontent.com/98423516/154539382-fac10968-eb0c-416a-ba17-d4740b63a565.png)

**Comment by franz134** [comment]
this doesn't help me, but maybe someone else understands it
found in `airgradient.h`
```
//ENUMS STRUCTS FOR CO2 START
    struct CO2_READ_RESULT {
    int co2 = -1;
    bool success = false;
};
//ENUMS STRUCTS FOR CO2 END
```

**Comment by Fwappy** [comment]
Also having this issue

**Comment by Benargee** [comment]
Yep also having this issue. If I restart the Wemos board it behaves for sometime before failing again with extreme high and low values.

**Comment by Fwappy** [comment]
Ok not a perfect solution, but adding these operators to the Prometheus query in Graphana makes the issue less visible for me
`< 5000 != 0 != -1 != 514 != 515 != 516 != 517 != 518`
![image](https://user-images.githubusercontent.com/11204286/158681049-f4fccd25-6711-4c3f-819f-521909f2a278.png)
something like this (my fork doesn't work exactly like Jeff's)

**Comment by andries230** [comment]
Exactly the same issue here. Started doing this after 2 days or so. I think it is caused by faulty communication between the sensor and the board resulting in the ‘default value’ being returned.

The exact values i am getting are 517 and -1. Those values follow each other up in that order after about 10 seconds. It repeats itself by doing this: 

0-9 seconds of correct measurements
0.5 seconds 517 
0.5 seconds -1

(my minimum interval between checks was 0.5 seconds)

**Comment by floyduk** [comment]
I have exactly the same problem on all 4 of my air gradient sensors. I wonder if the sensors made by AirGradient have the same issue. Seems like if they're using the same sensor. How are AirGradient dealing with this problem?

Like others I've been adding to my Grafana query to exclude certain results, which is a very unsatisfying solution. My bedroom air sensor query now looks like this in order to get rid of all the spikes: "rco2{job="airgradient-BedroomAir"} < 10000 > 0 != 513 != 514 != 515 != 516 != 517 != 518 != 519 != 520 != 521". Yes I could us a range.. but that's not the point.

I'm not up enough on the specs of this CO2 sensor but I wonder if it might have some way of signalling that it was unable to get a good reading. If not then could the code be modified to discard readings that are too far from previous readings to be plausible? It seems as though the sketch could be doing more to catch rogue values and avoid reporting them.

**Comment by floyduk** [comment]
Just having a browse through the code. Sorry for the idiot questions but Arduino programming is new to me. It looks as though the raw CO2 value comes from a function in AirGradient library - getCO2_Raw(). Anyone know how I get a look at that code?

**Comment by floyduk** [comment]
So here's the code from AirGradient.cpp that implements getCO2() and getCO2_Raw(). It seems we could eliminate some errors simply by using getCO2() instead of getCO2_Raw(). Clearly getCO2() implements a retry until it gets a valid value. I'm not sure this would fix our 513-521 range outlier values. But it's a start.

<img width="416" alt="image" src="https://user-images.githubusercontent.com/1799030/166679347-ed094ffe-36ac-4508-958d-8d689e28c871.png">

**Comment by Cutyno** [comment]
I ran into the same problem, but solved it by simply returning the old (valid) value. But as pointed out by @geerlingguy, it's not that beneficial to not know that there is a problem in the first place. I rewrote the sketch to exclude sensors when they report an error. You can find my solution at 2e59aed until the PR #29 goes through

**Comment by Benargee** [comment]
@floyduk 

Just a addon to your comment with direct GitHub link to that section of code

https://github.com/airgradienthq/arduino/blob/0b8408ef134c9569410270dd7e4f9db65c4222c8/AirGradient.cpp#L592-L631
