### ISSUE TITLE
Docker container not accepting POST request

### ISSUE THREAD

**Issue by ArnaudKunzi** [geerlingguy/airgradient-prometheus#8]
First of all, thanks to Jeff for your amazing work and all the documentation work you do, it's fantastic and deeply appreciated as I learn a lot from it!

I have the same problem as #6 I think.

I logged into the serial port of the device and noticed that the POST request got 404'ed too.

I managed to get the error code to change to 403 by hopping into the container and creating the folder /var/www/html/sensors/airgradient:d024a3/measures/ as well as changing the permissions with ```chown -R 33:33``` .
but for some reason the container do not 'accept' the POST request:

```
{"wifi":-69,"pm02":2,"rco2":1151,"atmp":23.20,"rhum":35}
http://192.168.1.15:9926/sensors/airgradient:d024a3/measures
301
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://192.168.0.9:9925/sensors/airgradient:d024a3/measures/">here</a>.</p>
<hr>
<address>Apache/2.4.51 (Debian) Server at 192.168.0.9 Port 9925</address>
</body></html>
```

My guess is that this has to do with the changes done in the last pull request to support multiple airgradient devices, but that the docker run command needs to be updated. Is this accurate? How could I go into debugging my issue?

**Comment by deathlessdd** [comment]
This might help you out delete  /airgradient:d024a3/measures then it will work.

**Comment by jorddenn** [comment]
I had the same problem as #6 but it's because the Docker commands pull a generic "php:8-apache" image. It's looking for files that are in the Git repo, in the "/var/www/html" directory. I created and copied the contents of "index.php", "metrics", and ".htaccess" into the html directory and it started seeing 200 from the POST requests in the logs. I also pointed Prometheus at the "/metrics" endpoint and was receiving data successfully.

One other thing to note is the Docker CLI and Compose seem to run different commands so I combined them into

docker run -d -p 9925:80 --name airgradient -v /path/to/direcotry:/var/www/html php:8-apache /bin/bash -c 'mkdir /sensors; chown -R 33:33 /sensors; chown -R 33:33 html; a2enmod rewrite; apache2-foreground'

making sure to set the directory to bind. In the CLI from the README this is "-v "$PWD":/var/www/html"

**Comment by ArnaudKunzi** [comment]
Spot on @jorddenn ! I just had realized that index.php was not in the /var/www/html/ folder and had just put it there when I saw your message. I added "metrics" and ".htaccess" and started seing 200 status right away!

For future other un-informed and confused readers: the .ino file instructs the device to http POST under the URL http://containeraddress:port/sensors/airgradient:d024a3/measures
But the index.php script placed at the root of the website (/var/www/html/) intercepts the request, read the path ( $_GET['path'] ), and if the base folder is '/sensors', then it processes the POST request. When you query http://containeraddress:port/metrics, you do not query a folder but the php file 'metrics' which serves you the information stored and processed by index.php.
Given that these files are not exported by the container build instruction provided, you get 404 if you try to POST or GET at these endpoints. 

I will propose a PR with a modified docker-compose file.
